<?php
/**
 * Cmsbox.fr Magento 2 Cmcic Payment.
 *
 * PHP version 7
 *
 * @category  Cmsbox
 * @package   Cmcic
 * @author    Cmsbox Development Team <contact@cmsbox.fr>
 * @copyright 2019 Cmsbox.fr all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.cmsbox.fr
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magento\Payment\Block\Transparent\Form $block
 */

// Get the block data
$isAdmin = $block->getData('is_admin');
$moduleName = $block->getData('module_name');
$methodId = ($block->getMethodCode()) ? $block->getMethodCode() : $block->getData('method_id');
$templateName = $block->getData('template_name');
$formCssFile = $this->assetRepository->createAsset($moduleName . '::css/payment_form/' . $templateName . '.css', ['area' => 'adminhtml'])->getUrl();
?>
<style>
    @import url(<?= $formCssFile ?>);

    .card-form-container {
        background-color: <?= $this->config->params[$methodId][$templateName . '_background_color']; ?>;
        border-width: <?= $this->config->params[$methodId][$templateName . '_border_width']; ?>;
        border-color: <?= $this->config->params[$methodId][$templateName . '_border_color']; ?>;
        border-radius: <?= $this->config->params[$methodId][$templateName . '_corner_radius']; ?>;
        box-shadow: 1px 2px 3px 0px <?= $this->config->params[$methodId][$templateName . '_shadow_color']; ?>;
    }

    .card-form-container .cvv-input input,
    .card-form-container .card-owner,
    .card-form-container .card-number,
    .card-form-container .month select,
    .card-form-container .year select {
        border-width: <?= $this->config->params[$methodId][$templateName . '_border_width']; ?>;
    }

    .card-form-container .form-header {
        border-bottom-width: <?= $this->config->params[$methodId][$templateName . '_border_width']; ?>;
        border-bottom-color: <?= $this->config->params[$methodId][$templateName . '_border_color']; ?>;
    }

    .card-form-container .title {
        color: <?= $this->config->params[$methodId][$templateName . '_label_color']; ?>;
    }

    .card-form-container .card-owner,
    .card-form-container .card-number,
    .card-form-container .cvv-details,
    .card-form-container .cvv-input input,
    .card-form-container .month select,
    .card-form-container .year select {
        color: <?= $this->config->params[$methodId][$templateName . '_input_text_color']; ?>;
        background-color: <?= $this->config->params[$methodId][$templateName . '_input_background_color']; ?>;
    }

    .card-form-container .card-owner,
    .card-form-container .card-number,
    .card-form-container .month select,
    .card-form-container .year select,
    .card-form-container .cvv-input input  {
        border-color: <?= $this->config->params[$methodId][$templateName . '_border_color']; ?>;
        border-radius: <?= $this->config->params[$methodId][$templateName . '_corner_radius']; ?>;
    }

    .card-form-container input.mage-error {
        border-color: <?= $this->config->params[$methodId][$templateName . '_error_color']; ?> !important;
    }
</style>

<?php if ($isAdmin) : ?>
    <fieldset class="admin__fieldset payment-method <?= /* @noEscape */ $methodId ?>" id="payment_form_<?= /* @noEscape */ $methodId ?>" style="display: none;">
<?php endif; ?>

    <div class="card-form-container">
        <div class="form-header">
            <h4 class="title">
                <?= $block->escapeHtml(__($this->config->params[$methodId][$templateName . '_form_title'])); ?>
            </h4>
        </div>
        <div class="form-body">
            <!-- Card Owner -->
            <div class="control">
                <input type="text"
                    name="card_data[owner]"
                    class="card-owner"
                    placeholder="<?= $block->escapeHtml(__('Card owner name')); ?>"
                    title="<?= $block->escapeHtml(__('Card owner name')) ?>"
                    data-validate="{'required-entry':true}"
                    >
            </div>

            <!-- Card Number -->
            <div class="control">
                <input type="number"
                    name="card_data[number]"
                    class="card-number"
                    placeholder="<?= $block->escapeHtml(__('Card number')); ?>"
                    title="<?= $block->escapeHtml(__('Card number')) ?>"
                    data-validate="{'required-entry':true, 'validate-cc-number':true}"
                    >
            </div>

            <!-- Date Field -->
            <div class="date-field">
                <div class="month">
                    <select name="card_data[month]" data-validate="{'required-entry':true, 'validate-card-date':true}">
                        <?php foreach ($block->months as $k => $v): ?>
                            <option value="<?= /* @noEscape */ $block->escapeHtml(sprintf("%02d", $k)) ?>">
                                <?= $block->escapeHtml($v) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="year">
                    <select name="card_data[year]" data-validate="{'required-entry':true, 'validate-card-year':true}">
                        <?php foreach ($block->years as $k => $v): ?>
                            <option value="<?= /* @noEscape */ $block->escapeHtml($v) ?>">
                                <?= $block->escapeHtml($v) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            
            <!-- Card Verification Field -->
            <?php if ($this->config->params[$methodId]['cvv_check_customer']): ?>
                <div class="card-verification">
                    <div class="cvv-input">
                        <input type="text" 
                               name="card_data[cvv]"
                               placeholder="<?= $block->escapeHtml(__('CVV')) ?>"
                               data-validate="{'required-entry':true, 'validate-number':true, 'validate-card-cvv':true}"
                        >
                    </div>
                    <div class="cvv-details">
                        <p><?= $block->escapeHtml(__('3 or 4 digits usually found on the signature strip')); ?></p>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>

<?php if ($isAdmin) : ?>
    </fieldset>
<?php endif; ?>

<script>
    //<![CDATA[
    require(
        [
            'jquery',
            'uiComponent',
            'domReady!',
            'Magento_Payment/js/model/credit-card-validation/validator',
            'mage/validation'
        ], function($, Component) {
            return Component.extend({
                validateForm: function (form) {
                    return $(form).validation() && $(form).validation('isValid');
                }
            });
        });
    //]]>
</script>