<?php
/**
 * Cmsbox.fr Magento 2 Cmcic Payment.
 *
 * PHP version 7
 *
 * @category  Cmsbox
 * @package   Cmcic
 * @author    Cmsbox Development Team <contact@cmsbox.fr>
 * @copyright 2019 Cmsbox.fr all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.cmsbox.fr
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magento\Payment\Block\Transparent\Form $block
 */

// Get the block data
$isAdmin = $block->getData('is_admin');
$moduleName = $block->getData('module_name');
$methodId = ($block->getMethodCode()) ? $block->getMethodCode() : $block->getData('method_id');
$templateName = $block->getData('template_name');
$formCssFile = $this->assetRepository->createAsset($moduleName . '::css/payment_form/' . $templateName . '.css', ['area' => 'adminhtml'])->getUrl();
?>
<style>
    @import url(<?= $formCssFile ?>);

    .card-form-container {
        background: <?= $this->config->params[$methodId][$templateName . '_background_color']; ?>;
        border-width: <?= $this->config->params[$methodId][$templateName . '_border_width']; ?>;
        border-color: <?= $this->config->params[$methodId][$templateName . '_border_color']; ?>;
        border-radius: <?= $this->config->params[$methodId][$templateName . '_corner_radius']; ?>;
        -webkit-box-shadow: 0 1px 5px <?= $this->config->params[$methodId][$templateName . '_shadow_color']; ?>;
        box-shadow: 0 1px 5px <?= $this->config->params[$methodId][$templateName . '_shadow_color']; ?>;
    }   

    .card-form-container .checkout-title {
        color: <?= $this->config->params[$methodId][$templateName . '_label_color']; ?>;
        text-shadow: 0 1px <?= $this->config->params[$methodId][$templateName . '_shadow_color']; ?>;
        background: <?= $this->config->params[$methodId][$templateName . '_background_color']; ?>;
        border-bottom-color: <?= $this->config->params[$methodId][$templateName . '_border_color']; ?>;
        border-bottom-width: <?= $this->config->params[$methodId][$templateName . '_border_width']; ?>;
        border-radius: <?= $this->config->params[$methodId][$templateName . '_corner_radius']; ?> <?= $this->config->params[$methodId][$templateName . '_corner_radius']; ?> 0 0;
        background-image: -webkit-linear-gradient(top, <?= $this->config->params[$methodId][$templateName . '_background_color']; ?>, <?= $this->config->params[$methodId][$templateName . '_background_color']; ?>);
        background-image: -moz-linear-gradient(top, <?= $this->config->params[$methodId][$templateName . '_background_color']; ?>, <?= $this->config->params[$methodId][$templateName . '_background_color']; ?>);
        background-image: -o-linear-gradient(top, <?= $this->config->params[$methodId][$templateName . '_background_color']; ?>, <?= $this->config->params[$methodId][$templateName . '_background_color']; ?>);
        background-image: linear-gradient(to bottom, <?= $this->config->params[$methodId][$templateName . '_background_color']; ?>, <?= $this->config->params[$methodId][$templateName . '_background_color']; ?>);
    }

    .card-form-container .checkout-title:before {
        -webkit-box-shadow: 0 1px 2px <?= $this->config->params[$methodId][$templateName . '_shadow_color']; ?>;
        box-shadow: 0 1px 2px <?= $this->config->params[$methodId][$templateName . '_shadow_color']; ?>;
    }

    .card-form-container .checkout-input {
        float: left;
        padding: 0 7px;
        height: 32px;
        color: <?= $this->config->params[$methodId][$templateName . '_input_text_color']; ?>;
        background-color: <?= $this->config->params[$methodId][$templateName . '_input_background_color']; ?>;
        border-color: <?= $this->config->params[$methodId][$templateName . '_border_color']; ?>;
        border-radius: <?= $this->config->params[$methodId][$templateName . '_corner_radius']; ?>;
        border-width: <?= $this->config->params[$methodId][$templateName . '_border_width']; ?>;
        -webkit-box-shadow: inset 0 1px 2px <?= $this->config->params[$methodId][$templateName . '_shadow_color']; ?>, 0 1px <?= $this->config->params[$methodId][$templateName . '_shadow_color']; ?>;
        box-shadow: inset 0 1px 2px <?= $this->config->params[$methodId][$templateName . '_shadow_color']; ?>, 0 1px <?= $this->config->params[$methodId][$templateName . '_shadow_color']; ?>;
    }

    .card-form-container :-moz-placeholder {
        color: <?= $this->config->params[$methodId][$templateName . '_label_color']; ?> !important;
    }

    .card-form-container ::-moz-placeholder {
        color: <?= $this->config->params[$methodId][$templateName . '_label_color']; ?> !important;
        opacity: 1;
    }

    .card-form-container ::-webkit-input-placeholder {
        color: <?= $this->config->params[$methodId][$templateName . '_label_color']; ?> !important;
    }

    .card-form-container :-ms-input-placeholder {
        color: <?= $this->config->params[$methodId][$templateName . '_label_color']; ?> !important;
    }

    .card-form-container input.mage-error {
        border-color: <?= $this->config->params[$methodId][$templateName . '_error_color']; ?> !important;
    }
    
    .card-form-container .checkout-input:focus {
        border-color: <?= $this->config->params[$methodId][$templateName . '_border_color']; ?>;
        -webkit-box-shadow: inset 0 1px 2px <?= $this->config->params[$methodId][$templateName . '_shadow_color']; ?>, 0 0 5px <?= $this->config->params[$methodId][$templateName . '_shadow_color']; ?>;
        box-shadow: inset 0 1px 2px <?= $this->config->params[$methodId][$templateName . '_shadow_color']; ?>, 0 0 5px <?= $this->config->params[$methodId][$templateName . '_shadow_color']; ?>;
    }
</style>

<?php if ($isAdmin) : ?>
    <fieldset class="admin__fieldset payment-method <?= /* @noEscape */ $methodId ?>" id="payment_form_<?= /* @noEscape */ $methodId ?>" style="display: none;">
<?php endif; ?>

<div class="card-form-container">
    <div class="checkout-header">
        <h1 class="checkout-title">
            <?= $block->escapeHtml(__($this->config->params[$methodId][$templateName . '_form_title'])); ?>
        </h1>
    </div>
    <p>
        <input type="text" 
               class="checkout-input checkout-name"
               placeholder="<?= $block->escapeHtml(__('Card owner name')); ?>"
               name="card_data[owner]"
               data-validate="{'required-entry':true}"
               >
        <input type="text"
               class="checkout-input checkout-exp month"
               placeholder="<?= $block->escapeHtml(__('MM')); ?>"
               name="card_data[month]"
               maxlength="2"
               data-validate="{'required-entry':true, 'validate-card-date':true}"
               >
        <input type="text"
               class="checkout-input checkout-exp year"
               placeholder="<?= $block->escapeHtml(__('YYYY')); ?>"
               name="card_data[year]"
               maxlength="4"
               data-validate="{'required-entry':true, 'validate-card-year':true}"
               >
    </p>
    <p>
        <input type="text"
               class="checkout-input checkout-card"
               placeholder="<?= $block->escapeHtml(__('Card number')); ?>"
               name="card_data[number]"
               data-validate="{'required-entry':true, 'validate-cc-number':true}"
               title="<?= $block->escapeHtml(__('Card number')) ?>"
               >
        <?php if ($this->config->params[$methodId]['cvv_check_customer']): ?>
            <span class="cvc-container">
                <input type="text"
                    name="card_data[cvv]"
                    class="checkout-input checkout-cvc"
                    maxlength="4"
                    placeholder="<?= $block->escapeHtml(__('CVV')); ?>"
                    data-validate="{'required-entry':true, 'validate-number':true, 'validate-card-cvv':true}"
                    >
            </span>
        <?php endif; ?>
    </p>
</div>

<?php if ($isAdmin) : ?>
    </fieldset>
<?php endif; ?>

<script>
    //<![CDATA[
    require(
        [
            'jquery',
            'uiComponent',
            'domReady!',
            'Magento_Payment/js/model/credit-card-validation/validator',
            'mage/validation'
        ], function($, Component) {
            return Component.extend({
                validateForm: function (form) {
                    return $(form).validation() && $(form).validation('isValid');
                }
            });
        });
    //]]>
</script>