<!--
/**
 * Naxero.com Magento 2 Monetico Payment.
 *
 * PHP version 7
 *
 * @category  Naxero
 * @package   Monetico
 * @author    Naxero Development Team <contact@naxero.com>
 * @copyright 2019 Naxero.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
-->

<div class="payment-method" data-bind="css: {'_active': (getCode() == isChecked())}">
    <div class="payment-method-title field choice">
        <input type="radio" name="payment[method]" class="radio" data-bind="attr: {'id': getCode()}, value: getCode(), checked: isChecked, click: selectPaymentMethod, visible: isRadioButtonVisible()" />
        <label class="label" data-bind="attr: {'for': getCode()}">
            <span data-bind="text: getTitle()"></span>
        </label>
    </div>

    <div class="payment-method-content">
        <div class="message" style="display: none"></div>
        <div>
            <form class="form" data-bind="attr: {id: targetForm, action: config.api_url}" method="POST" novalidate="novalidate" style="display:none">
                <input name="Data" data-bind="attr: {value: config.request_data.params}">
                <input name="InterfaceVersion" data-bind="attr: {value: config.interface_version_charge}">
                <input name="Seal" data-bind="attr: {value: config.request_data.seal}">
            </form>
            <iframe id="targetIframe" data-bind="attr: {visible: createIframe(), width: config.iframe_width, height: config.iframe_height, frameborder: config.iframe_border}" style="display:none;">
            </iframe>
            <br>
        </div>

        <div class="payment-method-billing-address">
            <!-- ko foreach: $parent.getRegion(getBillingAddressFormName()) -->
            <!-- ko template: getTemplate() -->
            <!-- /ko -->
            <!--/ko-->
        </div>

        <div class="checkout-agreements-block">
            <!-- ko foreach: $parent.getRegion('before-place-order') -->
            <!-- ko template: getTemplate() -->
            <!-- /ko -->
            <!--/ko-->
        </div>

        <div class="actions-toolbar">
            <div class="primary">
                <button class="cancel action primary checkout" type="submit" data-bind="
                        id: targetButton,
                        click: beforePlaceOrder,
                        attr: {title: $t(config.button_label)},
                        css: {disabled: !isPlaceOrderActionAllowed()},
                        enable: (getCode() == isChecked())
                        " disabled>
                    <span data-bind="i18n: config.button_label"></span>
                </button>
            </div>
        </div>
    </div>
</div>